# Generated by Django 4.0.2 on 2022-02-19 18:19

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(default='incomplete', max_length=60),
        ),
        migrations.AlterField(
            model_name='projects',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_path),
        ),
    ]
