# Generated by Django 4.0.2 on 2022-02-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_category_alter_projects_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='completed',
        ),
    ]
