# Generated by Django 4.0.2 on 2022-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projects_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default='https://github.com/rruan7?tab=repositories'),
        ),
        migrations.AddField(
            model_name='projects',
            name='picture_link',
            field=models.URLField(default='https://user-images.githubusercontent.com/71851361/155896993-a3549ad7-fa6a-4822-baf5-dc9322a5997a.PNG'),
        ),
    ]
