# Generated by Django 4.0.2 on 2022-03-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_link_projects_picture_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='link',
            new_name='source_code',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='picture',
        ),
        migrations.AddField(
            model_name='projects',
            name='app_link',
            field=models.URLField(default='https://www.reneeruan.com'),
        ),
    ]
